### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Surestito** [Donno1994/TapWallet#24]
I try reaching out to you on Twitter but I can't I don't know if we can talk business sir it would be a big privilege for me having a one on one discussion with I got something to offer kindly text me on my WhatsApp or drop any means of communication here +1- 323 374 5290

**Comment by Donno1994** [comment]
I saw you're posting the same on different github repositories, so I don't think this is legit.
My DMs on twitter are open, you can contact me on https://twitter.com/BR_Robin.
I will not give away my phone number.

Greetings,
Robin

**Comment by Surestito** [comment]
It’s a privilege having you reply me sir kindly check your Twitter messages
I wrote you there already sir

**Comment by Donno1994** [comment]
I was happy to help!
Kind regards.

**Comment by Surestito** [comment]
Awesome, thanks!

**Comment by Donno1994** [comment]
I'm sorry, but I don't have time for that.
And I also don't make any money with this work.
There are many online courses that you could check out.
